from flask import Flask, request, render_template, make_response
import pickle
from sklearn.preprocessing import LabelEncoder
import numpy as np

app = Flask(__name__)

# Load model
model = pickle.load(open('best_model_XGBoost.pkl', 'rb'))

# Define CATEGORIES
CATEGORIES = {
    'PNK16': [
        'Rawat Inap di R. Perawatan Biasa', 'Evakuasi medis / Ambulans Darat',
        'Gula Darah Puasa (GDP) - PRB/Prolanis', 'Evakuasi medis / Ambulans Air',
        'Pelayanan pra-rujukan pada komplikasi kebidanan dan neonatal',
        'Kolesterol LDL', 'Kolesterol HDL', 'Ureum', 'HbA1c', 'Kreatinin',
        'Kolesterol Trigliserida', 'Microalbuminaria', 'Kolesterol Total',
        'Pelayanan KB : Pemasangan IUD / Implant',
        'Pelayanan KB : Cabut IUD / Implant', 'Pelayanan PNC 2 (Dua)',
        'Pelayanan KB : Suntik',
        'Paket Persalinan per Vaginam normal (oleh Bidan)',
        'Pelayanan ANC 2 (Dua)', 'Pelayanan ANC 3 (Tiga)', 'PSA - Obturasi',
        'PSA - Preparasi', 'Rontgen Periapikal', 'PSA - Dressing',
        'Pelayanan PNC 1 (Satu)', 'Pelayanan PNC 4 (Empat)',
        'Pelayanan ANC 1 (Satu)', 'Pelayanan ANC 4 (Empat)',
        'Paket Persalinan per Vaginam dengan tindakan emergensi dasar',
        'Pelayanan tindakan pasca persalinan',
        'Paket Persalinan per Vaginam normal (oleh Dokter)',
        'Pelayanan PNC 3 (Tiga)',
        'Pelayanan KB : Cabut & Pemasangan IUD / Implant'
    ],
    'PNK11': ['RITP', 'RJTP', 'PROMOTIF'],
    'PNK13A': {
        'A01': 'Kolera akibat vibrio cholerae',
        'A02': 'Infeksi salmonella lainnya',
        'A04': 'Infeksi bakteri usus lainnya',
        'A05': 'Keracunan makanan bakteri lainnya',
        'A06': 'Amebiasis',
        'A07': 'Protozoa usus lainnya',
        'A09': 'Gastroenteritis dan kolitis yang diduga infeksi',
        'A15': 'Tuberkulosis pernafasan, dikonfirmasi secara bakteriologi',
        'A16': 'Tuberkulosis pernafasan, tidak dikonfirmasi secara bakteriologi',
        'A17': 'Tuberkulosis susunan saraf',
        'A18': 'Tuberkulosis organ lainnya',
        'A22': 'Antraks',
        'A30': 'Kusta (penyakit hansen)',
        'A35': 'Tetanus lainnya',
        'A38': 'Demam scarlet',
        'A40': 'Sepsis streptokokus',
        'A41': 'Sepsis lainnya',
        'A49': 'Infeksi bakteri pada tempat tidak tertentu',
        'A68': 'Demam kambuh',
        'A75': 'Tifus murin',
        'A78': 'Demam Q',
        'A88': 'Infeksi virusus lainnya pada sistem saraf pusat, tidak diklasifikasikan di tempat lain',
        'A90': 'Demam berdarah dengue (DBD) klasik',
        'A91': 'Demam berdarah dengue (DBD) dengan renjatan',
        'A92': 'Demam virus lainnya yang ditularkan melalui nyamuk',
        'A94': 'Demam virus, ditularkan melalui arthropoda, tidak spesifik',
        'A95': 'Demam kuning',
        'A96': 'Demam arenavirus hemoragik',
        'A99': 'Demam virus hemoragik, tidak spesifik',
        'B05': 'Campak',
        'B15': 'Hepatitis akut A',
        'B16': 'Hepatitis akut B',
        'B19': 'Hepatitis virus, tidak spesifik',
        'B20': 'Penyakit virus human immunodeficiency (HIV)',
        'B24': 'Penyakit virus human immunodeficiency (HIV), tidak spesifik',
        'B34': 'Infeksi virus, tidak spesifik',
        'B39': 'Koksidioidomikosis',
        'B50': 'Malaria falciparum',
        'B51': 'Malaria vivax',
        'B54': 'Malaria, tidak spesifik',
        'C02': 'Keganasan lidah, bagian lain dan tidak spesifik',
        'C16': 'Keganasan lambung',
        'C18': 'Keganasan kolon',
        'C22': 'Keganasan hati dan saluran empedu intrahepatik',
        'C34': 'Keganasan bronkus dan paru',
        'C49': 'Keganasan jaringan ikat dan jaringan lunak lainnya',
        'C50': 'Keganasan payudara',
        'C53': 'Keganasan serviks uteri',
        'C56': 'Keganasan ovarium',
        'C71': 'Keganasan otak',
        'C76': 'Keganasan lokasi lain dan tidak spesifik',
        'D21': 'Neoplasma jinak jaringan ikat dan jaringan lunak lainnya',
        'D24': 'Neoplasma jinak payudara',
        'D25': 'Leiomioma uteri',
        'D26': 'Neoplasma jinak uterus lainnya',
        'D27': 'Neoplasma jinak ovarium',
        'D45': 'Poliitemia vera',
        'D46': 'Sindroma mielodisplastik',
        'D50': 'Anemia defisiensi besi',
        'D53': 'Anemia nutrisional lainnya',
        'D55': 'Anemia akibat gangguan enzim',
        'D59': 'Anemia hemolitik didapat',
        'D63': 'Anemia pada penyakit kronik',
        'D64': 'Anemia lainnya',
        'D69': 'Purpura dan keadaan hemoragik lainnya',
        'D72': 'Kelainan lain sel darah putih',
        'E04': 'Gondok bukan toksik lainnya',
        'E05': 'Tirotoksikosis (hipertiroidisme)',
        'E07': 'Kelainan kelenjar tiroid lainnya',
        'E10': 'Diabetes mellitus tergantung insulin',
        'E11': 'Diabetes mellitus tidak tergantung insulin',
        'E12': 'Diabetes mellitus terkait malnutrisi',
        'E13': 'Diabetes mellitus lainnya yang spesifik',
        'E14': 'Diabetes mellitus, tidak spesifik',
        'E15': 'Koma hipoglikemik non-diabetik',
        'E16': 'Gangguan sekresi hormon pankreas internal lainnya',
        'E45': 'Retardasi perkembangan akibat malnutrisi protein-energi',
        'E63': 'Defisiensi nutrisi lainnya',
        'E79': 'Gangguan metabolisme purin dan pirimidin',
        'E80': 'Gangguan metabolisme porfirin dan bilirubin',
        'E86': 'Kekurangan volume cairan',
        'E87': 'Gangguan keseimbangan cairan, elektrolit dan keseimbangan asam-basa lainnya',
        'F01': 'Demensia vaskular',
        'F10': 'Gangguan mental dan perilaku akibat alkohol',
        'F20': 'Skizofrenia',
        'F25': 'Gangguan skizoafektif',
        'F29': 'Psikosis nonorganik lainnya, tidak spesifik',
        'F43': 'Reaksi terhadap stres berat dan gangguan penyesuaian',
        'F44': 'Gangguan disosiatif (konversi)',
        'F45': 'Gangguan somatoform',
        'F50': 'Gangguan makan',
        'F53': 'Gangguan mental dan perilaku pada masa nifas, tidak diklasifikasikan di tempat lain',
        'G03': 'Meningitis akibat penyebab lain dan tidak spesifik',
        'G40': 'Epilepsi',
        'G44': 'Sindroma nyeri kepala lainnya',
        'G45': 'Serangan iskemik serebral transien dan sindroma terkait',
        'G46': 'Sindroma vaskular serebral pada penyakit serebrovaskular',
        'G47': 'Gangguan tidur',
        'G50': 'Gangguan nervus trigeminus',
        'G81': 'Hemiplegia',
        'G82': 'Paraplegia dan tetraplegia',
        'G93': 'Kelainan otak lainnya',
        'G99': 'Kelainan sistem saraf lainnya pada penyakit yang diklasifikasikan di tempat lain',
        'H25': 'Katarak senilis',
        'H26': 'Katarak lainnya',
        'H81': 'Gangguan fungsi vestibuler',
        'H82': 'Sindroma vertiginosa pada penyakit yang diklasifikasikan di tempat lain',
        'I10': 'Hipertensi esensial (primer)',
        'I11': 'Penyakit jantung hipertensi',
        'I12': 'Penyakit ginjal hipertensi',
        'I15': 'Hipertensi sekunder',
        'I20': 'Angina pektoris',
        'I21': 'Infark miokard akut',
        'I24': 'Penyakit jantung iskemik akut lainnya',
        'I25': 'Penyakit jantung iskemik kronik',
        'I47': 'Takikardia paroksismal',
        'I48': 'Fibrilasi dan flutter atrium',
        'I49': 'Gangguan irama jantung lainnya',
        'I50': 'Gagal jantung',
        'I51': 'Komplikasi dan gambaran tidak jelas penyakit jantung',
        'I52': 'Kelainan jantung lainnya pada penyakit yang diklasifikasikan di tempat lain',
        'I60': 'Perdarahan subaraknoid',
        'I61': 'Perdarahan intraserebral',
        'I63': 'Infark serebral',
        'I64': 'Stroke, tidak spesifik sebagai perdarahan atau infark',
        'I67': 'Penyakit serebrovaskular lainnya',
        'I69': 'Sekuel penyakit serebrovaskular',
        'I77': 'Kelainan arteri dan arteriol lainnya',
        'I84': 'Hemoroid',
        'I86': 'Varises lainnya',
        'I95': 'Hipotensi',
        'J00': 'Nasofaringitis akut (common cold)',
        'J02': 'Faringitis akut',
        'J03': 'Tonsilitis akut',
        'J06': 'Infeksi akut saluran pernafasan bagian atas, multiple dan tidak spesifik',
        'J11': 'Influenza, virus tidak teridentifikasi',
        'J12': 'Pneumonia virus, tidak diklasifikasikan di tempat lain',
        'J15': 'Pneumonia bakteri, tidak diklasifikasikan di tempat lain',
        'J16': 'Pneumonia akibat organisme lainnya',
        'J18': 'Pneumonia, organisme tidak spesifik',
        'J20': 'Bronkitis akut',
        'J21': 'Bronkiolitis akut',
        'J35': 'Penyakit kronik tonsil dan adenoid',
        'J36': 'Peritonsilar abses',
        'J40': 'Bronkitis, tidak spesifik sebagai akut atau kronik',
        'J42': 'Bronkitis kronik yang tidak spesifik',
        'J44': 'Penyakit paru obstruktif kronik lainnya',
        'J45': 'Asma',
        'J46': 'Status asmatikus',
        'J47': 'Bronkiektasis',
        'J68': 'Kondisi pernafasan akibat inhalasi bahan kimia, gas, asap dan uap',
        'J80': 'Sindroma gawat nafas dewasa',
        'J81': 'Edema paru',
        'J90': 'Efusi pleura, tidak diklasifikasikan di tempat lain',
        'J93': 'Pneumotoraks',
        'K02': 'Karies gigi',
        'K04': 'Penyakit pulpa dan jaringan periapikal',
        'K12': 'Stomatitis dan lesi terkait',
        'K21': 'Penyakit refluks gastroesofageal (GERD)',
        'K22': 'Kelainan esophagus lainnya',
        'K25': 'Ulkus gaster (lambung)',
        'K27': 'Ulkus peptik, lokasi tidak spesifik',
        'K28': 'Ulkus gastrojejunal',
        'K29': 'Gastritis dan duodenitis',
        'K30': 'Dispepsia',
        'K31': 'Kelainan lain lambung dan duodenum',
        'K35': 'Apendisitis akut',
        'K36': 'Apendisitis lainnya',
        'K37': 'Apendisitis, tidak spesifik',
        'K38': 'Kelainan lain apendiks',
        'K40': 'Hernia inguinalis',
        'K46': 'Hernia abdomen lainnya',
        'K52': 'Gastroenteritis dan kolitis non-infeksi lainnya',
        'K56': 'Ileus paralitik dan obstruksi usus tanpa hernia',
        'K59': 'Konstipasi lainnya',
        'K61': 'Abses anus dan rektum',
        'K62': 'Kelainan lain anus dan rektum',
        'K70': 'Penyakit hati alkoholik',
        'K73': 'Hepatitis kronik, tidak diklasifikasikan di tempat lain',
        'K74': 'Fibrosis dan sirosis hati',
        'K75': 'Penyakit hati inflamasi lainnya',
        'K80': 'Kolelitiasis',
        'K81': 'Kolesistitis',
        'K83': 'Kelangan saluran empedu lainnya',
        'K90': 'Malabsorpsi usus',
        'K92': 'Penyakit sistem pencernaan lainnya',
        'L02': 'Abses kulit, furunkel dan karbunkel',
        'L03': 'Selulitis',
        'L10': 'Pemfigus',
        'L20': 'Dermatitis atopik',
        'L23': 'Dermatitis alergi kontak',
        'L24': 'Dermatitis iritan kontak',
        'L50': 'Urtikaria',
        'L51': 'Eritema multiforme',
        'L89': 'Ulkus dekubitus',
        'M06': 'Artritis reumatoid lainnya',
        'M10': 'Gout',
        'M19': 'Artrosis lainnya',
        'M25': 'Kelainan sendi lainnya, tidak diklasifikasikan di tempat lain',
        'M32': 'Lupus eritematosus sistemik',
        'M35': 'Kelainan lain pada jaringan ikat sistemik',
        'M51': 'Kelangan discus intervertebralis lainnya',
        'M54': 'Nyeri punggung',
        'M62': 'Kelangan otot lainnya',
        'M66': 'Ruptur spontan sinovia dan tendon',
        'M79': 'Kelangan jaringan lunak lainnya, tidak diklasifikasikan di tempat lain',
        'M99': 'Lesi biomekanik, tidak diklasifikasikan di tempat lain',
        'N00': 'Sindroma nefritik akut',
        'N11': 'Pielonefritis kronik',
        'N13': 'Uropati obstruktif dan refluks',
        'N17': 'Gagal ginjal akut',
        'N18': 'Penyakit ginjal kronik',
        'N20': 'Kalkulus ginjal dan ureter',
        'N21': 'Kalkulus saluran kemih bawah',
        'N23': 'Kolik renal, tidak spesifik',
        'N30': 'Sistitis',
        'N34': 'Uretritis dan sindroma uretra',
        'N39': 'Kelangan lain sistem kemih',
        'N40': 'Hiperplasia prostat',
        'N73': 'Penyakit radang panggul perempuan lainnya',
        'N83': 'Kelangan non-inflamasi ovarium, tuba fallopii dan ligamen latum',
        'N90': 'Kelangan non-neoplastik lainnya vulva',
        'N91': 'Menstruasi tidak ada, sedikit dan jarang',
        'N92': 'Menstruasi berlebihan, sering dan tidak teratur',
        'N93': 'Perdarahan abnormal lain dari uterus dan vagina',
        'N94': 'Nyeri dan keadaan lain terkait organ genital perempuan',
        'N97': 'Infertilitas pada perempuan',
        'O00': 'Kehamilan ektopik',
        'O01': 'Mola hidatidosa',
        'O02': 'Produk konsepsi abnormal lainnya',
        'O03': 'Abortus spontan',
        'O04': 'Abortus medis',
        'O05': 'Abortus lainnya',
        'O06': 'Abortus tidak spesifik',
        'O08': 'Komplikasi akibat abortus, kehamilan ektopik dan mola hidatidosa',
        'O10': 'Hipertensi yang sudah ada sebelumnya yang memburuk pada kehamilan, persalinan dan nifas',
        'O12': 'Edema dan proteinuria gestasional (hipertensi gestasional)',
        'O13': 'Hipertensi gestasional (tanpa proteinuria signifikan)',
        'O14': 'Hipertensi gestasional dengan proteinuria signifikan (preeklampsia)',
        'O15': 'Eklampsia',
        'O16': 'Hipertensi maternal, tidak spesifik',
        'O20': 'Perdarahan pada awal kehamilan',
        'O21': 'Hiperemesis gravidarum',
        'O26': 'Perawatan maternal untuk kondisi lain yang terkait kehamilan',
        'O28': 'Temuan abnormal pada skrining antenatal maternal',
        'O30': 'Kehamilan multipel',
        'O32': 'Perawatan maternal untuk presentasi janin abnormal',
        'O33': 'Perawatan maternal untuk disproporsi',
        'O34': 'Perawatan maternal untuk kelangan bentuk atau ukuran pelvis abnormal',
        'O35': 'Perawatan maternal untuk kelangan dan kerusakan janin yang diketahui atau dicurigai',
        'O36': 'Perawatan maternal untuk masalah lain pada janin',
        'O41': 'Kelangan lain cairan ketuban dan membran',
        'O42': 'Ketuban pecah dini',
        'O44': 'Plasenta previa',
        'O46': 'Perdarahan antepartum lainnya',
        'O47': 'Persalinan palsu',
        'O48': 'Kehamilan lewat waktu',
        'O60': 'Persalinan prematur',
        'O61': 'Gagalnya induksi persalinan',
        'O62': 'Gangguan his persalinan',
        'O63': 'Persalinan lama',
        'O64': 'Persalinan terhambat akibat presentasi janin abnormal',
        'O65': 'Persalinan terhambat akibat kelangan pelvis maternal',
        'O66': 'Persalinan terhambat lainnya',
        'O67': 'Persalinan dan persalinan dengan komplikasi perdarahan intrapartum, tidak diklasifikasikan di tempat lain',
        'O68': 'Persalinan dan persalinan dengan komplikasi gawat janin',
        'O69': 'Persalinan dan persalinan dengan komplikasi tali pusat',
        'O70': 'Ruptur perineum selama persalinan',
        'O71': 'Trauma obstetrik lainnya',
        'O72': 'Perdarahan pasca persalinan',
        'O73': 'Retensi plasenta dan selaput tanpa perdarahan',
        'O75': 'Komplikasi lain persalinan dan persalinan, tidak diklasifikasikan di tempat lain',
        'O80': 'Persalinan spontan tunggal',
        'O81': 'Persalinan dengan vakum ekstraktor atau forseps',
        'O82': 'Persalinan dengan seksio sesarea',
        'O83': 'Persalinan dengan bantuan operasi lainnya',
        'O84': 'Persalinan multipel',
        'O85': 'Sepsis puerperal',
        'O86': 'Infeksi puerperal lainnya',
        'O88': 'Emboli obstetrik',
        'O89': 'Komplikasi anestesi selama masa puerperal',
        'O90': 'Komplikasi masa puerperal, tidak diklasifikasikan di tempat lain',
        'O94': 'Sekuel komplikasi kehamilan, persalinan dan nifas',
        'O98': 'Penyakit infeksi dan parasitik maternal yang memperberat kehamilan, persalinan dan nifas',
        'O99': 'Penyakit lain maternal yang memperberat kehamilan, persalinan dan nifas',
        'P00': 'Janin dan neonatus yang dipengaruhi oleh kondisi maternal yang tidak berhubungan dengan kehamilan saat ini',
        'P01': 'Janin dan neonatus yang dipengaruhi oleh komplikasi maternal kehamilan',
        'P02': 'Janin dan neonatus yang dipengaruhi oleh komplikasi plasenta, tali pusat dan membran',
        'P05': 'Pertumbuhan janin lambat dan malnutrisi janin',
        'P07': 'Gangguan yang berhubungan dengan masa gestasi pendek dan berat lahir rendah',
        'P08': 'Gangguan yang berhubungan dengan masa gestasi panjang dan berat lahir tinggi',
        'P22': 'Gangguan pernafasan pada neonatus',
        'P24': 'Sindroma aspirasi neonatus',
        'P28': 'Gangguan pernafasan lainnya pada neonatus',
        'P56': 'Hydrops fetalis akibat hemolisis',
        'P59': 'Penyakit kuning neonatal lainnya',
        'P75': 'Ileus mekonium',
        'P80': 'Hipotermia pada neonatus',
        'P95': 'Kematian janin akibat penyebab tidak spesifik',
        'P96': 'Kondisi lain yang berasal dari periode perinatal',
        'Q13': 'Kelangan kongenital segmen anterior mata',
        'Q21': 'Kelangan septum jantung kongenital',
        'Q24': 'Kelangan jantung kongenital lainnya',
        'Q80': 'Ichthyosis congential',
        'R00': 'Kelangan irama jantung, tidak spesifik',
        'R04': 'Perdarahan saluran nafas',
        'R05': 'Batuk',
        'R06': 'Kelangan pernafasan lainnya',
        'R07': 'Nyeri tenggorokan dan dada',
        'R09': 'Gejala dan tanda lain pada sistem sirkulasi dan pernafasan',
        'R10': 'Nyeri abdomen dan panggul',
        'R11': 'Mual dan muntah',
        'R13': 'Disfagia',
        'R15': 'Inkontinensia alvi',
        'R16': 'Hepatomegali dan splenomegali, tidak diklasifikasikan di tempat lain',
        'R17': 'Penyakit kuning tidak spesifik',
        'R18': 'Asites',
        'R19': 'Gejala dan tanda lain pada sistem pencernaan dan abdomen',
        'R23': 'Perubahan kulit lainnya',
        'R31': 'Hematuria tidak spesifik',
        'R33': 'Retensi urin',
        'R40': 'Somnolence, stupor dan koma',
        'R41': 'Gejala dan tanda lain pada fungsi kognitif dan kesadaran',
        'R42': 'Pusing dan pingsan',
        'R50': 'Demam penyebab lain yang tidak diketahui',
        'R51': 'Sakit kepala',
        'R53': 'Malaise dan kelelahan',
        'R54': 'Senilitas',
        'R56': 'Kejang, tidak diklasifikasikan di tempat lain',
        'R57': 'Syok, tidak diklasifikasikan di tempat lain',
        'R59': 'Pembesaran kelenjar getah bening',
        'R60': 'Edema, tidak diklasifikasikan di tempat lain',
        'R63': 'Gejala dan tanda lain mengenai asupan makanan dan cairan',
        'R73': 'Peningkatan kadar glukosa darah',
        'R90': 'Temuan abnormal pada pencitraan diagnostik sistem saraf pusat',
        'S00': 'Luka superficial kepala',
        'S01': 'Luka terbuka kepala',
        'S02': 'Fraktur tulang kepala dan wajah',
        'S03': 'Dislokasi, strain dan strain sendi dan ligamen kepala',
        'S06': 'Cedera intrakranial',
        'S07': 'Crushing injury kepala',
        'S09': 'Cedera kepala lainnya dan tidak spesifik',
        'S20': 'Cedera superficial dada',
        'S29': 'Cedera dada lainnya dan tidak spesifik',
        'S30': 'Cedera superficial abdomen, punggung bawah dan pelvis',
        'S32': 'Fraktur tulang belakang lumbal dan pelvis',
        'S42': 'Fraktur skapula dan tulang panjang lengan',
        'S43': 'Dislokasi, strain dan strain sendi dan ligamen gelang bahu',
        'S52': 'Fraktur tulang lengan bawah',
        'S61': 'Luka terbuka pergelangan tangan dan tangan',
        'S62': 'Fraktur pada tingkat pergelangan tangan dan tangan',
        'S82': 'Fraktur tungkai bawah, termasuk pergelangan kaki',
        'S86': 'Cedera otot dan tendon pada tingkat tungkai bawah',
        'S88': 'Traumatic amputation tungkai bawah',
        'S91': 'Luka terbuka pergelangan kaki dan kaki',
        'S92': 'Fraktur kaki, kecuali pergelangan kaki',
        'T01': 'Luka multiple melibatkan multiple body regions',
        'T14': 'Cedera pada bagian tubuh tidak spesifik',
        'T30': 'Luka bakar pada bagian tubuh tidak spesifik',
        'T31': 'Luka bakar diklasifikasikan menurut luas permukaan tubuh yang terkena',
        'T38': 'Keracunan oleh obat, medicament dan zat biologis lainnya',
        'T50': 'Keracunan oleh diuretik dan obat lainnya',
        'T60': 'Keracunan oleh pestisida',
        'T63': 'Efek toksik dari kontak dengan hewan beracun',
        'T70': 'Efek tekanan udara dan tekanan air',
        'T81': 'Komplikasi prosedur, tidak diklasifikasikan di tempat lain',
        'T82': 'Komplikasi alat bantu jantung dan vaskular',
        'T88': 'Komplikasi lain perawatan medis dan bedah, tidak diklasifikasikan di tempat lain',
        'V25': 'Pengendara sepeda motor terluka dalam tabrakan dengan kereta api atau kendaraan beroda',
        'V45': 'Kecelakaan lalu lintas lainnya',
        'W57': 'Digigit atau disengat oleh serangga tidak beracun dan arthropod lainnya',
        'W59': 'Digigit atau dihancurkan oleh reptil',
        'Y42': 'Efek samping hormon dan penggantinya',
        'Y76': 'Efek samping alat bantu ginekologi dan obstetrik',
        'Z00': 'Pemeriksaan kesehatan umum',
        'Z01': 'Pemeriksaan khusus dan penyelidikan lainnya',
        'Z02': 'Pemeriksaan untuk tujuan administratif',
        'Z03': 'Observasi medis dan evaluasi untuk kondisi yang dicurigai',
        'Z08': 'Follow-up examination setelah pengobatan untuk neoplasma',
        'Z09': 'Follow-up examination setelah pengobatan untuk kondisi lainnya',
        'Z11': 'Skrining khusus untuk penyakit infeksi dan parasitik',
        'Z20': 'Kontak dengan dan paparan penyakit menular',
        'Z23': 'Kebutuhan untuk imunisasi terhadap penyakit bakteri tunggal',
        'Z25': 'Kebutuhan untuk imunisasi terhadap penyakit virus tunggal',
        'Z27': 'Kebutuhan untuk imunisasi kombinasi terhadap penyakit infeksi',
        'Z28': 'Imunisasi tidak dilakukan',
        'Z30': 'Kontrasepsi',
        'Z31': 'Fertilisasi',
        'Z32': 'Pemeriksaan kehamilan',
        'Z33': 'Kehamilan sebagai temuan insidental',
        'Z34': 'Pemantauan kehamilan normal',
        'Z35': 'Pemantauan kehamilan dengan riwayat obstetri atau reproduksi yang bermasalah',
        'Z36': 'Skrining antenatal',
        'Z37': 'Hasil persalinan',
        'Z38': 'Bayi lahir hidup menurut tempat lahir',
        'Z39': 'Perawatan dan pemeriksaan pasca persalinan',
        'Z45': 'Penyesuaian dan manajemen alat bantu',
        'Z48': 'Perawatan follow-up lainnya',
        'Z52': 'Donor organ dan jaringan',
        'Z61': 'Masalah terkait pengabaian dan pengasuhan anak yang tidak adekuat',
        'Z63': 'Masalah lainnya terkait keluarga',
        'Z64': 'Masalah terkait dengan keadaan psikososial',
        'Z71': 'Konsultasi lainnya',
        'Z74': 'Masalah terkait ketergantungan pada penyedia layanan',
        'Z85': 'Riwayat pribadi neoplasma',
        'Z87': 'Riwayat pribadi penyakit lainnya',
        'Z92': 'Riwayat pribadi pengobatan',
        'Z93': 'Kondisi ostomi',
        'Z95': 'Keberadaan alat bantu jantung dan vaskular',
        'Z96': 'Keberadaan implan lainnya',
        'Z97': 'Keberadaan alat bantu lainnya',
        'Z98': 'Kondisi pasca bedah lainnya'
    },
    'PNK14': {
        'A01': 'Inspeksi dan palpasi',
        'A010': 'Inspeksi umum',
        'A014': 'Palpasi abdomen',
        'A020': 'Pemeriksaan neurologis dasar',
        'A049': 'Pemeriksaan telinga, hidung, tenggorokan',
        'A04': 'Pemeriksaan fisik umum',
        'A042': 'Pemeriksaan mata',
        'A059': 'Pemeriksaan kulit',
        'A060': 'Pemeriksaan kardiovaskular',
        'A069': 'Pemeriksaan pernafasan',
        'A07': 'Pemeriksaan laboratorium darah',
        'A09': 'Pemeriksaan laboratorium urin',
        'A099': 'Pemeriksaan feses',
        'A090': 'Analisis urin lengkap',
        'A159': 'Rontgen thorax',
        'A15': 'Pemeriksaan radiologi',
        'A150': 'Rontgen extremitas',
        'A152': 'Rontgen abdomen',
        'A156': 'USG abdomen',
        'A160': 'USG obstetric',
        'A16': 'Pemeriksaan ultrasonografi',
        'A170': 'EKG (Elektrokardiogram)',
        'A179': 'Ekokardiografi',
        'A182': 'CT Scan kepala',
        'A222': 'MRI',
        'A30': 'Terapi inhalasi',
        'A35': 'Nebulizer',
        'A38': 'Oksigenasi',
        'A40': 'Infus cairan',
        'A419': 'Transfusi darah',
        'A418': 'Pemberian obat intravena',
        'A499': 'Pemberian obat intramuskular',
        'A49': 'Pemberian obat parenteral',
        'A68': 'Pemasangan kateter urine',
        'A759': 'Pemasangan NGT',
        'A75': 'Prosedur gastrointestinal',
        'A78': 'Jahit luka',
        'A881': 'Pemasangan gips',
        'A90': 'Ekstraksi gigi',
        'A91': 'Scaling gigi',
        'A920': 'Tambal gigi',
        'A929': 'Pembersihan luka',
        'A94': 'Insisi dan drainase abses',
        'A959': 'Biopsi',
        'A969': 'Endoskopi',
        'A99': 'Prosedur bedah minor'
    },
    'PNK10': [
        'KLINIK RAWAT INAP', 'RAWAT INAP', 'NON RAWAT INAP', 'RS KELAS D PRATAMA',
        'KLINIK NON RAWAT INAP', 'DOKTER PRAKTEK PERORANGAN', 'LABORATORIUM', '99',
        'PPK LAIN-LAIN'
    ]
}

# Create LabelEncoders
le_pnk16 = LabelEncoder().fit(CATEGORIES['PNK16'])
le_pnk11 = LabelEncoder().fit(CATEGORIES['PNK11'])
le_pnk13a = LabelEncoder().fit(sorted(CATEGORIES['PNK13A'].keys()))
le_pnk14 = LabelEncoder().fit(sorted(CATEGORIES['PNK14'].keys()))
le_pnk10 = LabelEncoder().fit(CATEGORIES['PNK10'])

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        pnk16 = request.form['PNK16']
        pnk11 = request.form['PNK11']
        pnk13a = request.form['PNK13A']
        pnk14 = request.form['PNK14']
        pnk10 = request.form['PNK10']

        # Encode
        encoded = [
            le_pnk16.transform([pnk16])[0],
            le_pnk11.transform([pnk11])[0],
            le_pnk13a.transform([pnk13a])[0],
            le_pnk14.transform([pnk14])[0],
            le_pnk10.transform([pnk10])[0]
        ]

        prediction = model.predict(np.array([encoded]))[0]

        return f'<h1>Prediction: {prediction}</h1><br><a href="/">Back</a>'

    return render_template('index.html', categories=CATEGORIES)

@app.route('/game')
def game():
    return render_template('game.html')

@app.route('/404.html')
def not_found_page():
    response = make_response(render_template('404.html'), 404)
    response.headers['Cache-Control'] = 'public, max-age=300'  # Cache for 5 minutes
    return response

@app.errorhandler(404)
def page_not_found(e):
    response = make_response(render_template('404.html'), 404)
    response.headers['Cache-Control'] = 'public, max-age=300'  # Cache for 5 minutes
    return response

if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True)
